# Generated by Django 4.2 on 2024-07-23 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
