# Generated by Django 4.2 on 2024-07-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_time_created_todo_time_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='time_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='done',
            new_name='is_done',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='time_updated',
            new_name='updated_at',
        ),
    ]
